#!/bin/bash

HAXELIB_PATH="`cat $HOME/.haxelib`"
AWE6_PATH="$HAXELIB_PATH/awe6"
if [ -d "$AWE6_PATH" ];then

  # Test if there are 3 arguments

  if [ "$#" -eq 3 ]; then

    FILE_FULL="$1"
    PACKAGE_NAME="$2"
    DEFAULT_USER="$3"
    CBI=" "
    CSLB=""

    # Remove extension

    FILE_FULL="`echo -n $FILE_FULL | sed -e 's/.hx$//'`"

    # Extract file path

    FILE_NAME="`echo -n $FILE_FULL | sed -e 's/^.*\///'`"
    FILE_BASE="`echo -n $FILE_FULL | sed -e "s/$FILE_NAME$//"`"

    # Extract file extension

    CLASS_NAME="$FILE_NAME"
    FILE_NAME="$FILE_NAME.hx"
    FILE_FULL="$FILE_FULL.hx"

    # Test if base directory exists

    if [ -d "$FILE_BASE" ];then

      # and go there

      cd "$FILE_BASE"

      # Test if file already exists

      if [ -f "$FILE_NAME" ];then
        echo "File $FILE_FULL already exists"
      else
        AWE6_PATH="$AWE6_PATH/`cat $AWE6_PATH/.current | sed -e 's/\./,/g'`"
        RES_PATH="$AWE6_PATH/__resources"

        unzip -p "$RES_PATH/flashDevelop.zip" */Entity.hx.fdt | sed \
          -e "s/\$(DefaultUser)/$DEFAULT_USER/" \
          -e "s/\$(FileName)/$CLASS_NAME/" \
          -e "s/\$(Package)/$PACKAGE_NAME/" \
          -e "s/\$(CBI)/$CBI/" \
          -e "s/\$(CSLB)/$CSLB/" \
        >"$FILE_NAME"
        echo "Entity $FILE_FULL successfully created"
      fi
    else
      echo "Directory $FILE_BASE doesn't exists"
    fi
  else
    echo "Syntax: $0 <EntityName> <PackageName> <AuthorName>"
  fi
else
  echo "Project awe6 not installed.\nPlease run 'haxelib install awe6'"
fi
